export enum charactersActionType {
    FETCH_CHARACTERS = "FETCH_CHARACTERS",
    FETCH_CHARACTERS_SUCCESS = "FETCH_CHARACTERS_SUCCESS",
    FETCH_CHARACTERS_ERROR = "FETCH_CHARACTERS_ERROR",
    SET_CHARACTERS_PAGE = "SET_CHARACTERS_PAGE"
}